/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2016-11-15 11:10:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;
import javax.servlet.http.*;
import javax.servlet.*;

public final class SendSubmittedEmail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

  String result;
  // 获取表单提交的收件人地址
  String to = request.getParameter("to");
  // 获取表单提交的发件人地址
  String from = request.getParameter("from");
  // 获取表单提交的邮件标题
  String subject = new String(request.getParameter("subject").getBytes("ISO-8859-1"), "UTF-8");
  // 获取表单提交的邮件文本正文
  String messageText = new String(request.getParameter("body").getBytes("ISO-8859-1"), "UTF-8");
  // 获取邮件服务器地址
  String host = request.getParameter("host");
  if (host == null || host == "") host = "localhost";
  // 获取邮件服务器登陆用户名
  String usr = request.getParameter("user");
  // 获取邮件服务器登陆密码
  String pwd = request.getParameter("password");
  // 获取系统属性对象
  Properties properties = System.getProperties();
  // 设置邮件服务器地址
  properties.setProperty("mail.smtp.host", host);
  // 设置邮件服务器登陆用户名
  properties.setProperty("mail.user", usr);
  // 设置邮件服务器登陆密码
  properties.setProperty("mail.password", pwd);
  // 获取默认的 Session 对象
  Session mailSession = Session.getDefaultInstance(properties);
  
  try {
	  // 创建一个默认的 MimeMessage 对象
	  MimeMessage message = new MimeMessage(mailSession);
	  // 设置 FROM 字段
	  message.setFrom(new InternetAddress(from));
	  // 设置 TO 字段
	  message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
	  // 设置 SUBJECT 字段
	  message.setSubject(subject);
	  // 设置文本消息正文
	  message.setText(messageText);
	  // 发送消息
	  Transport.send(message);
	  result = "成功发送消息....";
  } catch (MessagingException mex) {
	  mex.printStackTrace();
	  result = "错误：无法发送消息....";
  }

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("  <title>使用 JSP 发送电子邮件</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <center>\r\n");
      out.write("    <h1>使用 JSP 发送电子邮件</h1>\r\n");
      out.write("  </center>\r\n");
      out.write("  <center>\r\n");
      out.write("    <p>");
 out.println("发送结果：" + result + "\n"); 
      out.write("</p>\r\n");
      out.write("  </center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
